version: 2
jobs:
  build:
    machine: true
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Clone test project
          working_directory: ~/
          command: |
            (git -C ~/codacy-plugins-test fetch --all &&
              git -C ~/codacy-plugins-test reset --hard origin/master) ||
                git clone git://github.com/codacy/codacy-plugins-test.git ~/codacy-plugins-test
      - run:
          name: Compile test project
          working_directory: ~/codacy-plugins-test
          command: sbt compile
      - run:
          name: Publish tool docker locally
          working_directory: ~/workdir
          command: ./build.sh
      - run:
          name: Test json
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.ignore.descriptions=true "run-main codacy.plugins.DockerTest json codacy/$CIRCLE_PROJECT_REPONAME:latest"
      - run:
          name: Test patterns
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.noremove=true -Dcodacy.tests.threads=8 "run-main codacy.plugins.DockerTest pattern codacy/$CIRCLE_PROJECT_REPONAME:latest"
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag codacy/${CIRCLE_PROJECT_REPONAME}:latest codacy/$CIRCLE_PROJECT_REPONAME:1.0.$CIRCLE_BUILD_NUM
              docker push codacy/$CIRCLE_PROJECT_REPONAME:1.0.$CIRCLE_BUILD_NUM
              docker push codacy/$CIRCLE_PROJECT_REPONAME:latest
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build